http-post.md

A small change, but without the quotes, the `&` will be treated syntactically in any bourne-style shell.

The & should be quoted

---

libcurl-threading.md

Rather than duplicate the thread safety documentation in this book
provide a brief description and then refer to the thread safety webpage.
I think this is a safer move since the thread safety nuances are subject
to change, and the reader should always have the latest information.
Bug: https://curl.haxx.se/mail/lib-2017-04/0042.html
Reported-by: Vitaliy T

libcurl-threading.md: Refer to the thread safety webpage

---

http-cookies.md

Fixed a typo "exists -> exits"

http-cookies: fix typo

---

building-boringssl.md

Fix minor typo in the BoringSSL instructions

---

usingcurl-verbose.md

The list of available `--write-out` variables suffers from a slight case of "Wall of text" because the variable names are not in a distinguishably different format than the text describing them.
By marking the available variables as `code`, they become more distinctive.
(Alternatively, instead of displaying the names as `code`, they _could_ be displayed in **bold**).

Changes write-out variables to be more distinctive

---

building-source.md

Instructions to configure building against SecureTransport did not match https://github.com/bagder/everything-curl/blob/master/building-tls.md.

Fix SecureTransport build instruction.

---

get-curl-linux.md

Hello Daniel, 
I found that there is no installation instruction for Arch Linux, but the step to install curl on Arch Linux is quite easy, so I added the following instruction. 
Unless you have something else planned for this section, I think this can be added to the book.
Tell me what you think!
Thank you.
God bless!
Wayne Lai.

added installation instruction for Arch Linux

---

cmdline-passwords.md
cmdline-progressmeter.md

Three wording changes.
I think `in the plain` is correct but I added this change because the first read-through had me double checking. Open to interpretation.

fix wording

---

curl-etiquette.md

Remove unnecessary gender-slanting in discussion of mailing list etiquette.
I realize that "guys" **can** be used as a generic non-gendered term. As a "guy" myself, I use it that way all the time, though usually as a form of direct address ("hey, guys").
This is not one of those generic uses.
In fact, it sort of leaps off the page/screen at you when, towards the end of a long section on etiquette that's fairly neutral with its terminology, suddenly users of the mailing list are described as "[t]he guys who write answers".
It's unnecessary phrasing, and while the cURL project's [code of conduct](https://ec.haxx.se/opensource-coc.html) stops short of addressing issues of _bias_ (focusing mostly on the more damaging issue of harassment), I feel it reflects poorly on cURL.

[etiquette]: "the guys who" => "those who"

---

tls-sslkeylogfile.md

Wireshark switched to TLS as the protocol name. The user has to go to
Preferences->Protocols->TLS to set the master secrets file location.
Closes #xxxx

tls-sslkeylogfile: Fix Wireshark preferences protocol name s/SSL/TLS/

---

ftp-advanced.md

The unquoted command
curl -T image[1-99].jpg ftp://ftp.example.com/upload/
risks getting expanded by the shell before it is passed to curl, which would be equivalent to
curl -T image1.jpg image2.jpg [...] image99.jpg ftp://ftp.example.com/upload/
which would lead to curl treating the strings `image2.jpg` to `image99.jpg` to be treated as URLs.
I added quotes to pass the globbing characters to curl.

ftp-advanced.md: Quote globbing characters

---

http/requests.md

the readability of this sentence can be improved by using the proper possessive form 'its' vs the conjugated "it's." thank you for considering my suggestion

typo conjugated form instead of possessive

---

http/post.md

this paragraph can be improved by 1) omitting the statement that POST is not GET (this is fundamentally true insofar as the text of the method is one or the other and it is stated at the end of the paragraph) and 2) clarifying that the convenience comes from reusing the field information from a POST so that the luser doesn't have to manually add it end of the url on the command line. i have proposed my wording thus to accomplish these improvements. thank you for considering my suggestions.

superfluous statement and unclear sentence

---

http/response.md

this paragraph would be improved by changing 'sending' to 'receiving' as the topic is from the point of view of curl as the client and processing what has been received (i.e. the response header section and its the chunked body). thank you for considering my recommendation.

word inconsistent with topic

---

http/conditionals.md

- "time stamp" ➤ "timestamp"
- "been been" ➤ "been"
- "olso" ➤ "also"

Typo fixes

---

http/browserlike.md

Curl is effectively banned from some parts of WWW nowadays :(. Information about this could save some time for other people.

Add a note about TLS fingerprinting

---

libcurl/callbacks/write.md

Callback realloc() fails for uninitialized struct

---

usingcurl/downloads/retry.md

`--retry-max-time 120` should make cURL retry no more than 2 minutes

Update the explanation of --retry-max-time

---

usingcurl/verbose/writeout.md

json is a fairly new feature and a lot of places I run curl don't have a version high enough, so I see `curl: unknown --write-out variable: 'json'`. It's good to add when it was released.

json write-out introduced version

---

build.md
cmdline/differences.md
cmdline/passwords.md
http/http2.md
http/multipart.md
http/post/javascript.md
http/postvspost.md
internals/tests/curl.md
libcurl-http.md
libcurl-http/auth.md
libcurl-http/responses.md
libcurl-http/upload.md
libcurl/caches.md
libcurl/connectionreuse.md
libcurl/drive/multi-socket.md
libcurl/easyhandle.md
libcurl/examples/get.md
libcurl/names.md
libcurl/ws/read.md
source/contributing.md
usingcurl/downloads/whatis.md
usingcurl/uploads.md

To allow scripts to better deal with them

markdown: make all links single-line

---

usingcurl/transfers/rate-limiting.md

It uses an average per several seconds, not the entire transfer

usingcurl/transfers/rate-limiting.md: clarify the algo

---

index-words
usingcurl.md
usingcurl/ipfs.md
wordlist.txt

usingcurl/ipfs: add

---

http/post/simple.md

Reported-by: kidonng on github
Fixes #319

http/post/simple.md: clarify that -d @file skips CRLF

---

http/versions.md

Updates the link to the HTTP/3 document to correctly point to http3.md

Correct link to http3.md

---

cmdline/configfile.md

The indent on line 85 was preventing the link from displaying correctly on the live page, and some of the escape sequences on lines 102 - 103 ( \t, \n and \r ) were not showing up at all.

fixed syntax errors on line 85 and 103 - RE closed PR 374

---

http/browserlike.md
http/multipart.md
libcurl/control/meter.md
libcurl/control/ratelimit.md
libcurl/ws/meta.md
usingcurl/telnet.md
usingcurl/verbose.md

No other markdown escaping mechanisms for consistency. Also avoid "~~~c" simply because it does not work across all output versions we do.

all: use 4 space indents for examples

---

cmdline/configfile.md
cmdline/variables.md
libcurl/control/meter.md
libcurl/control/ratelimit.md
libcurl/control/stopslow.md
usingcurl/netrc.md
usingcurl/smtp.md
usingcurl/transfers/request-rate.md

They are often just unnecessary

misc: avoid "example" as subtitle

---

libcurl/getinfo.md
libcurl/options/all.md
usingcurl/verbose/writeout.md

Because of some peculiarity in pandoc it easily generates table columns that overlap when generating the PDF, which apparently can be tweaked by editing the length of the dashes on the top of the table.
But also: these tables possibly also show that they are not nice to do as tables when getting displayed in a page in a PDF as they have contents that make the columns very narrow. We should reconsider turning them into lists instead.
Fixes #418

tweak table headers for PDF output

---

http/post/browsersends.md

... instead of refering to Wireshark docs.

http/post/browsersends.md: link the SSLKEYLOGFILE section

---

cmdline/configfile.md
cmdline/variables.md

First of all, thank you for `curl` and the _everything curl_ guide.
In two locations where the backslash (`\`) was used, there was "forward slash" mentioned. These two occurrences have been fixed.

Fix: forward slash -> backslash for '\'

---

usingcurl/verbose/writeout.md

For some reason they have falled out.
Reported-by: ilmari
Bug: https://social.treehouse.systems/@ilmari/112087350148472781

usingcurl/verbose/writeout.md: add missing escaped examples

---

checkmd
usingcurl/uploads.md

Since mdBook turns them into 'index.html' they break the HTML version.

checkmd: detect and error on links to README.md

---

build/windows.md

We recommend using cmake to generate the build files. Also mention mingw support.

build/windows: remove custom visual studio mention, use cmake

---

.github/scripts/check-quotes.pl
cmdline/variables.md

I was reading the doc https://ec.haxx.se/cmdline/variables.html and I was suprised to see unicode quotes in the command line examples:
I've checked it with the latest version of curl and such usage gives an error:
```
bessarabov@bessarabov-osx:~$ docker run -it --rm docker.io/curlimages/curl --expand-url “https://example.com/{{path:trim}}”
Warning: The argument '“https://example.com/”' starts with a unicode quote
Warning: where maybe an ASCII " was intended?
curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
bessarabov@bessarabov-osx:~$
```
So I'm pretty sure that this is a misspell in the docs that should be fixed.
PS I don't think that the exact curl version will give any additional info, but just in case i'm providing it here.
``` …
```

Using ansi quotes in variables.md and CI bad-quote update

---

usingcurl/connections/README.md

Since curl can also use UDP and QUIC.

usingcurl/connections/README.md: rephrase without being TCP specific

---

SUMMARY.md
usingcurl/downloads/whatis.md

usingcurl/downloads/whatis.md: remove "exactly" from title

---

libcurl/caches.md

Because the support has wiedened and mentioning a long range of them becomes tedious in text.

libcurl/caches.md: remove mentioned CA caching backends

---

badwords.txt
build/autotools.md
cmdline/copyas.md
cmdline/exitcode.md
cmdline/urls/ftptype.md
cmdline/urls/globbing.md
helpers/sharing.md
http/post/multipart.md
http/put.md
http/redirects.md
http/response.md
install/container.md
install/linux.md
libcurl/globalinit.md
project/comm.md
protocols/http.md
transfers/conn/keepalive.md
transfers/drive/multi-socket.md
transfers/drive/multi.md
usingcurl/connections/keepalive.md
usingcurl/connections/name.md

badwords.txt: use the one used in the curl repo
