mkindex.pl

It wasn't quite clear to me whether the index generation should really be doing a case sensitive search for words. Doing so misses out lots of instances (e.g. TELNET misses the error code, cookies misses a ton of references, Javascript misses them all). On the other hand, this patch as-is causes a few wrong references (e.g. -u catches -U instances). Maybe index-words needs to be split into case sensitive and case insensitive sections.

mkindex: ignore case when search for words in the index

---

bindings.md

* Got the link information from https://curl.haxx.se/libcurl/bindings.html
* Checked and corrected all links to new web sites or additional authors added
* Removed dead-links or links that explicitly said was no longer maintained.
* Used table for formating for easy access of content

Flushed out bindings links and information.

---

usingcurl-connections.md
usingcurl-downloads.md
usingcurl-timeouts.md

A couple incorrect characters, one part of speech.

Assorted typo fixes

---

building-source.md

(building): Fix typo

---

curl-does.md

I found the wording of this paragraph difficult to understand. Thought this new wording helped clarify the intent.

clarify language

---

curl-started.md

... in "How it started" section.

Remove unneeded "a"

---

curl-bugs.md

...in "Reporting bugs" section.

Remove unneeded "to"

---

usingcurl-proxies.md

Reported-by: David Piano
Fixes #104

usingcurl-proxies.md: rephrase to clarify

---

usingcurl-smtp.md

...in "Using curl" -> "SMTP" -> "No MX lookup!" section.
Alternatively, "include with" can be replaced with "are".

Remove unnecessary "with"

---

README.md
bookindex.md
curl-bugs.md
opensource-devel.md
sourcecode-contributing.md
sourcecode-web.md
sourcecode.md

Typo fixes

---

usingcurl-tls.md

Remove confusion that caused https://github.com/curl/curl/issues/5515

Clarify non-default TLS backends

---

usingcurl-smtp.md

I have recently tried to use the commands herein, but they did not work.
I had to add the *--user* option to make them work, but that took me a lot of fo time and effort.
So, this is to help people get results easily

Make curl commands work

---

http-response.md

The `--writeout` section must have moved. So I fixed it :)

fix link http-response.md -> usingcurl-writeout.md

---

cmdline/options.md

Fix verb form

---

http/requests.md

i recommended changing 'intend', which is a verb, to the related adjective form 'intended'. thank you for considering my suggestion.

verb instead of participial adjective

---

http/redirects.md

this sentence's readability can be improved by combining 'run time' into the more common 'runtime'. thank you for considering my suggestion.

split word without hyphenation

---

http/postvspost.md

this sentence can be improved by ensuring plurality agreement by appending an s to the direct object, i.e. 'character'. thank you for considering my suggestion.

typo, plural form needed

---

http/versions.md

this sentence could be improved by replacing a word omission i.e. by adhering to the convention that instruct is followed by 'on', cf 'tell'. thank you for considering my suggestion.

idiomatic omission

---

usingcurl/version.md

Typo fixes : 
invidual ➤ individual
Microsft ➤ Microsoft

Several typo fixes

---

get/windows.md

Not sure if you have a Windows machine, but it would be interesting to hear if you got it to work using these instructions :)

Building with MSYS2

---

SUMMARY.md
internals.md
internals/structs.md

Copied from docs/INSTALL and somewhat refreshed

internals/structs.md: new section

---

SUMMARY.md
internals.md
internals/resolving.md

internals/resolving.md: new section

---

get/linux.md

nix menu level was one level to deep
Signed-off-by: Jonas Forsberg <jonas.forsberg@suse.com>

fix: nix menu level

---

usingcurl/connections/name.md

Fix typo in name.md

---

protocols/protocols.md

Was "...we bend the rules every so slightly..."
Now "...we bend the rules ever so slightly..."

change 'every so slightly' to 'ever so slightly'

---

SUMMARY.md
http.md
http/method.md

- move into its own section
- provide a TOC in the HTTP intro page

http method

---

SUMMARY.md
http/post/url-encode.md

http/post/url-encode.md: new title "URL encode data"

---

project/devteam.md
wordlist.txt

- mention no formal membership
- update the list of 10-committers

project/devteam.md: refresh

---

cmdline/listopts.md

And remove info about pre 7.73.0 curl.

cmdline/listopts.md: update the numbers

---

index-words
usingcurl/verbose/trace.md

Fixes #329
Addresses half of #326

usingcurl/verbose/trace.md: add --trace-config and --trace-ids

---

index-words
usingcurl/proxies/https.md

usingcurl/proxies/https.md: explain --proxy-http2

---

usingcurl/telnet.md
wordlist.txt

And remove vt as an acceptable word

telnet: quote vt100

---

index-words
usingcurl/tls/verify.md

usingcurl/tls/verify.md: mention --ca-native

---

Makefile
template.html

1. Add wrapper html for better viewing
2. Fix img src path to correct value

Fix images path in html output

---

usingcurl/version.md

To make them fit on a PDF page

usingcurl/version.md: word-wrap the quoted sections

---

cmdline/urls/trurl.md
get/container.md
http/browserlike.md
http/conditionals.md
http/multipart.md

to ensure they look proper also in PDF pages

wrap quoted sections before 80 columns

---

cmdline/curlver.md
cmdline/exitcode.md
cmdline/globbing.md
cmdline/urls/browsers.md
cmdline/urls/host.md
cmdline/urls/parallel.md
cmdline/urls/query.md
usingcurl/connections/name.md
usingcurl/downloads/browsers.md
usingcurl/downloads/compression.md
usingcurl/transfers/request-rate.md
usingcurl/uploads.md
usingcurl/verbose/trace.md
usingcurl/verbose/writeout.md

Makes several small text corrections for grammar / clarity.

Minor Text Clean Up

---

bindings/README.md

Reported-by: Jiang Wenjian
Fixes #456

bindings: change java link to a working one

---

ftp/upload.md
index-words
usingcurl/uploads.md

usingcurl/uploads.md: mention --append for FTP and SFTP

---

index-words
usingcurl/connections/keepalive.md

usingcurl/connections/keepalive.md: mention --keepalive-cnt

---

usingcurl/connections/happy.md
usingcurl/connections/interface.md
usingcurl/connections/timeout.md

Corrected minor typos in some markdowns

Fix of typos in some markdowns

---

http/post/json.md

ref: https://github.com/curl/curl/pull/15197
The same explanation as https://curl.se/docs/manpage.html#--json

Apply --json doc's fix

---

cmdline/differences.md
helpers/ws/concept.md

fix two typos
